# Generated by Django 5.0.4 on 2024-06-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_id',
        ),
    ]
